
perl_version=5.34
prefix=/usr
libdir=${prefix}/lib64
perldir=${libdir}/perl5/vendor_perl/${perl_version}

install:
	install -d ${perldir}/LaTeXML/Package/
	install -m 644 flammie.cls.ltxml ${perldir}/LaTeXML/Package/
